apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-python-basic-scjd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-python-basic-scjd
    app.kubernetes.io/part-of: test-app-htsn
  name: devfile-sample-python-basic-scjd
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: python-app
      app.kubernetes.io/instance: devfile-sample-python-basic-scjd
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: python-app
        app.kubernetes.io/instance: devfile-sample-python-basic-scjd
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-hgum-tenant/test-app-htsn/devfile-sample-python-basic-scjd@sha256:fd5b63dd986afdd2274c5a502c375231e066154b0c06a615c2c13835b71a4f88
        name: my-python
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
